### ISSUE TITLE
Choosing a network plot style

### ISSUE THREAD

**Issue by AlbanSagouis** [Rekyt/taxo_harmonization#1]
We have the choice between 2 styles for package and database networks:
 - keeping all packages (or databases) on-screen at all time and plotting only vertices between selected packages (or databases)
 - showing only selected packages (or databases) and the vertices between them, if any. If there are no vertices between selected packages (or databases), the current version of the app  (0de3369c9630e20978bff34eeb6b6f8c7528a9c0) fails to plot the packages (or databases).

**Comment by Rekyt** [comment]
To make things a little easier to read we could keep all networks complete but use an interactive network package such as [`visNetwork`](http://datastorm-open.github.io/visNetwork/) so that the users can navigate the links.

**Comment by Rekyt** [comment]
This has been fixed by 9853b8a44cf407c55d8558e2c250c741ddd78c4a
