### ISSUE TITLE
When resolving package dependencies: fail to download a deprecated package

### ISSUE THREAD

**Issue by AlbanSagouis** [Rekyt/taxo_harmonization#4]
In build_package_network.R, `pkg_deps$resolve()` and `pkg_deps$solve()` throw an error because one of the packages listed, `traitdataform` has been removed from CRAN on 2021-04-30.

Is this a critical issue? Should an archived version be installed?

**Comment by Rekyt** [comment]
Argh... Packages are thrown out of CRAN pretty easily these days...
One way would be to refer to the GitHub version; https://github.com/EcologicalTraitData/traitdataform

**Comment by Rekyt** [comment]
Fixed by e49a441a1
