### ISSUE TITLE
R package to add: `kewr`

### ISSUE THREAD

**Issue by barnabywalker** [Rekyt/taxo_harmonization#7]
Hi,

I just watched great @emilio-berti 's talk at TDWG 2021!

Would it be possible to add an R package I've put together? It's an R wrapper for Kew's data resources, called [`kewr`](https://barnabywalker.github.io/kewr/). It links to [IPNI](https://ipni.org/), [WCVP](https://wcvp.science.kew.org/) (which I don't think you have any entries for at the moment?), and [POWO](http://www.plantsoftheworldonline.org/).

Many thanks,
Baz

**Comment by barnabywalker** [comment]
That's fantastic, thank you!

**Comment by Rekyt** [comment]
Done for the revised version!
